<?xml version='1.0'?>

<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="chassis_width" value="0.098"/>
  <xacro:property name="chassis_length" value="0.14"/>
  <xacro:property name="chassis_height" value="0.05"/>
  <xacro:property name="chassis_mass" value="1"/>
  <xacro:property name="wheel_radius" value="0.02"/>
  <xacro:property name="wheel_width" value="0.01"/>
  <xacro:property name="wheel_mass" value="0.25"/>
  <xacro:property name="camera_link" value="0.007"/>
  <xacro:property name="height3" value="0.013"/>
  <xacro:property name="axel_offset" value="0.0"/>


  <!--<xacro:include filename="$(find enph353_ros_lab)/urdf/robot.gazebo" />-->
  <xacro:include filename="$(find enph353_ros_lab)/urdf/macros.xacro" />


  <!-- -->
  <link name='chassis'>

    <xacro:box_inertial name="chassis" m="${chassis_mass}" x="${chassis_width}" y="${chassis_length}" z="${chassis_height}"/>
    
    <collision name='chassis_collision'>
      <geometry>
        <box size="${chassis_width} ${chassis_length} ${chassis_height}"/>
      </geometry>
    </collision>

    <visual name='chassis_visual'>
      <origin xyz="0 0 0" rpy=" 0 0 0"/>
      <geometry>
        <box size="${chassis_width} ${chassis_length} ${chassis_height}"/>
      </geometry>
    </visual>
  </link>

  <link name="wheel_1">
    <xacro:cylinder_inertial name="wheel_1" m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    <collision>
      <origin xyz="0 0 0" rpy = "0 0 0" /> 
      <geometry>
        <cylinder radius="${wheel_radius}$" length="${wheel_width}$"/>
      </geometry>
    </collision>
    <visual name="wheel_1">
      <!-- <origin xyz="0.032 0.02 0.0" rpy="0.0 0.785375 0.0"/> -->
      <origin xyz="0 0 0" rpy = "0 0 0" /> 
      <geometry>
        <cylinder radius="${wheel_radius}$" length="${wheel_width}$"/>
      </geometry>
    </visual>
  </link>


  <joint name="wheel_joint_1" type="continuous">
    <parent link="chassis"/>
    <child link="wheel_1"/>
    <origin xyz="0.054 0.04 ${-1*chassis_height/2}" rpy="0.0 1.5708  0.0"/> 
    <axis xyz="0.0 0.0 -1.0"/>
  </joint>



  <link name="wheel_2">
    <xacro:cylinder_inertial name="wheel_2" m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wheel_radius}$" length="${wheel_width}$"/>
      </geometry>
    </collision>
    <visual name="wheel_2">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wheel_radius}$" length="${wheel_width}$"/>
      </geometry>
    </visual>
  </link>


  <joint name="wheel_joint_2" type="continuous">
    <parent link="chassis"/>
    <child link="wheel_2"/>
    <origin xyz="-0.054 0.04 ${-1*chassis_height/2}" rpy="0.0 -1.5708  0.0"/> 
    <axis xyz="0.0 0.0 1.0"/>
  </joint>


  <joint name="wheel_joint_3" type="continuous">
    <parent link="chassis"/>
    <child link="wheel_3"/>
    <origin xyz="0.054 -0.04 ${-1*chassis_height/2}" rpy="0.0 1.5708  0.0"/> 
    <axis xyz="0.0 0.0 -1.0"/>
  </joint>

  <link name="wheel_3">
    <xacro:cylinder_inertial name="wheel_3" m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    <collision>
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wheel_radius}$" length="${wheel_width}$"/>
      </geometry>
    </collision>
    <visual name="wheel_3">
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wheel_radius}$" length="${wheel_width}$"/>
      </geometry>
    </visual>
  </link>

  <joint name="wheel_joint_4" type="continuous">
    <parent link="chassis"/>
    <child link="wheel_4"/>
    <origin xyz="-0.054 -0.04 ${-1*chassis_height/2}" rpy="0.0 -1.5708  0.0"/> 
    <axis xyz="0.0 0.0 1.0"/>
  </joint>

  <link name="wheel_4">
    <xacro:cylinder_inertial name="wheel_1" m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
    <collision>
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wheel_radius}$" length="${wheel_width}$"/>
      </geometry>
    </collision>
    <visual name="wheel_4">
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <cylinder radius="${wheel_radius}$" length="${wheel_width}$"/>
      </geometry>
    </visual>
  </link>


  <joint name="camera_joint" type="fixed">
    <axis xyz="0 0 0" />
   <!-- <origin xyz="${camera_link} 0 ${height3 - axel_offset*2}" rpy="0 0 0"/> -->
    <origin xyz = "0 ${0.07+camera_link/2} 0" rpy = "0 0.52359877559 1.5708"/>
    <parent link="chassis"/>
    <child link="camera_link"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <collision>
      <origin xyz="0.0 0 0" rpy="0.0 0.0 0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0.0 0 0" rpy="0 0.0 0.0"/>
      <geometry>
    <box size="${camera_link} ${camera_link} ${camera_link}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <inertial>
      <mass value="1e-6" />
      <origin xyz="0.0 0 0" rpy="0 0.0 0.0"/>
      <origin xyz="0.0 0.07 0.025" rpy="0.0 0.0 0.0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

 <!-- camera -->
  <gazebo reference="camera_link">
    <sensor type="camera" name="camera1">
      <update_rate>30.0</update_rate>
      <camera name="head">
        <horizontal_fov>1.3962634</horizontal_fov>
        <image>
          <width>800</width>
          <height>800</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.02</near>
          <far>300</far>
        </clip>
        <noise>
          <type>gaussian</type>
          <!-- Noise is sampled independently per pixel on each frame.
               That pixel's noise value is added to each of its color
               channels, which at that point lie in the range [0,1]. -->
          <mean>0.0</mean>
          <stddev>0.00</stddev>
        </noise>
      </camera>
      <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>100</updateRate>
        <cameraName>rrbot/camera1</cameraName>
        <imageTopicName>image_raw</imageTopicName>
        <cameraInfoTopicName>camera_info</cameraInfoTopicName>
        <frameName>camera_link</frameName>
        <hackBaseline>0.07</hackBaseline>
        <distortionK1>0.0</distortionK1>
        <distortionK2>0.0</distortionK2>
        <distortionK3>0.0</distortionK3>
        <distortionT1>0.0</distortionT1>
        <distortionT2>0.0</distortionT2>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo>
    <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
      <updateRate>100.0</updateRate>
      <robotNamespace>/robot</robotNamespace>
      <leftFrontJoint>wheel_joint_2</leftFrontJoint>
      <rightFrontJoint>wheel_joint_1</rightFrontJoint>
      <leftRearJoint>wheel_joint_4</leftRearJoint>
      <rightRearJoint>wheel_joint_3</rightRearJoint>
      <wheelSeparation>0.108</wheelSeparation>
      <wheelDiameter>0.04</wheelDiameter>
      <robotBaseFrame>chassis</robotBaseFrame>
      <torque>20</torque>
      <topicName>cmd_vel</topicName>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <covariance_x>0.0001</covariance_x>
      <covariance_y>0.0001</covariance_y>
      <covariance_z>0.0001</covariance_z>
      <covariance_yaw>0.01</covariance_yaw>
      <broadcastTF>false</broadcastTF>
    </plugin>
  </gazebo>


  <gazebo reference="chassis">
    <material>Gazebo/Green</material>
  </gazebo>  

  <gazebo reference="wheel_1">
    <material>Gazebo/Black</material>
  </gazebo> 

  <gazebo reference="wheel_2">
    <material>Gazebo/Black</material>
  </gazebo> 


  <gazebo reference="wheel_3">
    <material>Gazebo/Black</material>
  </gazebo> 

  <gazebo reference="wheel_4">
    <material>Gazebo/Black</material>
  </gazebo> 

  <gazebo reference="camera_link">
    <material>Gazebo/Red</material>
  </gazebo> 

</robot>